version: "3"
services:
  zoo1:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ./data/zoo1:/data
      - ./datalog/zoo1:/datalog
      - ./config/zoo1:/conf
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
    image: zookeeper
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./data/zoo2:/data
      - ./datalog/zoo2:/datalog
      - ./config/zoo2:/conf
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo3:
    image: zookeeper
    restart: always
    ports:
      - 2183:2181
    volumes:
      - ./data/zoo3:/data
      - ./datalog/zoo3:/datalog
      - ./config/zoo3:/conf
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
