version: "3"
services:
  zoo1:
    image: zookeeper
    container_name: zoo1
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zoo1-data:/data
      - zoo1-datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
    image: zookeeper
    container_name: zoo2
    restart: always
    ports:
      - 2182:2181
    volumes:
      - zoo2-data:/data
      - zoo2-datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: always
    ports:
      - 2183:2181
    volumes:
      - zoo3-data:/data
      - zoo3-datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
volumes:
  zoo1-data:
  zoo2-data:
  zoo3-data:
  zoo1-datalog:
  zoo2-datalog:
  zoo3-datalog:

